os: osx
osx_image: xcode12.5
language: swift
script: xcodebuild clean build test -project PokemonEncyclopedia/PokemonEncyclopedia.xcodeproj -scheme "CI" -sdk iphonesimulator14.5 -destination "platform=iOS Simulator,OS=14.5,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUITED=NO
